/*
 * %! Copyright (C) 2011 Kei Suzuki  All rights reserved. !%
 * 
 * This file is part of Sevenri, a Clojure environment ("This Software").
 * 
 * The use and distribution terms for this software are covered by the Eclipse
 * Public License version 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
 * which can be found in the COPYING at the root of this distribution.
 * By using this software in any fashion, you are agreeing to be bound by the
 * terms of this license.
 * You must not remove this notice, or any other, from this software.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPanel.java
 *
 * Created on Aug 16, 2010, 10:51:46 PM
 */

package slix.sevenri.gui;

/**
 *
 * @author ksuzuki
 */
public class MainPanel extends javax.swing.JPanel {

    /** Creates new form MainPanel */
    public MainPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSevenri = new javax.swing.JPanel();
        lblSevenri = new javax.swing.JLabel();
        spDivider = new javax.swing.JSplitPane();
        spListSn = new javax.swing.JScrollPane();
        lstSn = new javax.swing.JList();
        spListName = new javax.swing.JScrollPane();
        lstName = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(300, 150));

        pnlSevenri.setBackground(new java.awt.Color(0, 0, 0));
        pnlSevenri.setPreferredSize(new java.awt.Dimension(400, 40));

        lblSevenri.setFont(new java.awt.Font("Times", 1, 16));
        lblSevenri.setForeground(new java.awt.Color(204, 204, 84));
        lblSevenri.setText("Sevenri-xx.xx.xx");

        org.jdesktop.layout.GroupLayout pnlSevenriLayout = new org.jdesktop.layout.GroupLayout(pnlSevenri);
        pnlSevenri.setLayout(pnlSevenriLayout);
        pnlSevenriLayout.setHorizontalGroup(
            pnlSevenriLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
            .add(pnlSevenriLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlSevenriLayout.createSequentialGroup()
                    .add(0, 144, Short.MAX_VALUE)
                    .add(lblSevenri)
                    .add(0, 144, Short.MAX_VALUE)))
        );
        pnlSevenriLayout.setVerticalGroup(
            pnlSevenriLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 40, Short.MAX_VALUE)
            .add(pnlSevenriLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlSevenriLayout.createSequentialGroup()
                    .add(0, 12, Short.MAX_VALUE)
                    .add(lblSevenri)
                    .add(0, 12, Short.MAX_VALUE)))
        );

        spDivider.setDividerLocation(190);

        spListSn.setViewportView(lstSn);

        spDivider.setLeftComponent(spListSn);

        spListName.setViewportView(lstName);

        spDivider.setRightComponent(spListName);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlSevenri, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, spDivider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(pnlSevenri, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(260, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(41, 41, 41)
                    .add(spDivider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblSevenri;
    public javax.swing.JList lstName;
    public javax.swing.JList lstSn;
    private javax.swing.JPanel pnlSevenri;
    public javax.swing.JSplitPane spDivider;
    private javax.swing.JScrollPane spListName;
    private javax.swing.JScrollPane spListSn;
    // End of variables declaration//GEN-END:variables

}
