#!/bin/bash

# Print usage

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "usage: clean [-h|--help|-v|--verbose] [-i|--sid [instance_name]]"
    exit 0
fi

verbose=nil

SevenriRoot=`pwd` # where is a Sevenri repo root directory

# Sanity check

if [ "`which lein`" == "" ]; then
    echo "This script requires Leiningen, lein."
    exit 1
fi

SevenriCljFileName="${SevenriRoot}/src/Sevenri.clj"

if [ ! -f $SevenriCljFileName ]; then
    echo "This script requires to run on a Sevenri repo root directory."
    exit 1
fi

# Optionally cleanup sid

SevenriInstanceName=""
SIDPath=""

for arg in $*; do
    case "${arg}" in
        "-v" | "--verbose") verbose=t ;;
        "-i" | "--sid") SevenriInstanceName="Sevenri" ;;
        *)  if [ "${SevenriInstanceName}" != "" ] && [ "${arg}" != "Sevenri" ]; then
            	SevenriInstanceName="Sevenri_${arg}"
            fi ;;
    esac
done

if [ "${SevenriInstanceName}" != "" ]; then
    SIDPath="${HOME}/.sevenri/${SevenriInstanceName}"
fi

# Helper functions

debug_msg()
{
    if [ $verbose == t ]; then
        echo $1
    fi
}

print_msg()
{
    echo $1
}

remove_path()
{
    debug_msg "rm -rf $1"
    rm -rf $1
}

remove_file_type_on_path()
{
    local type="*.$1"
    local path="$2"
    debug_msg "find ${path} -name ${type} -delete"
    find $path -name $type -delete
}

clean_lein_project()
{
    debug_msg "pushd $1"
    pushd $1 >/dev/null

    debug_msg "lein clean"
    lein clean >/dev/null
    remove_path ./lib
    remove_path ./pom.xml

    debug_msg "popd"
    popd >/dev/null
}

main()
{
    print_msg "Cleaning the Sevenri project..."
    clean_lein_project .

    print_msg "Removing src/library paths..."
    for path in "clojure" "incanter" "slix/incantea/data"; do
        print_msg $path
        remove_path ./src/library/$path
    done

    print_msg "Removing src/sevenri paths..."
    for path in "listeners/evtdelegator"; do
        print_msg $path
        remove_path ./src/sevenri/$path
    done

    print_msg "Removing .class files on src/sevenri/listeners..."
    remove_file_type_on_path "class" ./src/sevenri/listeners

    print_msg "Removing src/slix paths..."
    for path in "sevenri/jvm/gui/bin"; do
        print_msg $path
        remove_path ./src/slix/$path
    done

    print_msg "Cleaning src/project/slix projects..."
    for project in "documenter" "incantea" "planter"; do
        print_msg $project
        clean_lein_project ./src/project/slix/$project
    done

    if [ "${SIDPath}" != "" ]; then
        print_msg "Removing Sevenri instance directory: $SIDPath..."
        remove_path $SIDPath
    fi
}

# Start cleaning up stuff on $SevenriRoot

pushd $SevenriRoot >/dev/null
main
popd >/dev/null
