#!/bin/bash

# Print usage

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "usage: setup [-h|--help|-v|--verbose] [instance_name]"
    echo "Use the instance_name_SETUP_JVM_OPTS environment variable"
    echo "to preset extra JVM options."
    exit 0
fi

verbose=nil

SevenriRoot=`pwd` # where is a Sevenri repo root directory

# Sanity check

if [ "`which osacompile`" == "" ]; then
    echo "This script requires the AppleScript compiler, osacompile."
	exit 1
fi

if [ "`which lein`" == "" ]; then
    echo "This script requires Leiningen, lein."
    exit 1
fi

SevenriCljFileName="${SevenriRoot}/src/Sevenri.clj"
SevenriIconFileName="${SevenriRoot}/src/resources/images/icons/Sevenri-icon.icns"

if [ ! -f $SevenriCljFileName ] || [ ! -f $SevenriIconFileName ]; then
    echo "This script requires to run on a Sevenri repo root directory."
    exit 1
fi

# Prepare for creating a Sevenri.app from an AppleScript

SevenriInstanceName="Sevenri"

for arg in $*; do
    case "${arg}" in
        "-v" | "--verbose") verbose=t ;;
        *) SevenriInstanceName="Sevenri_${arg}" ;;
    esac
done

SevenriAppFileName="${SevenriRoot}/${SevenriInstanceName}.app"

if [ "$TMPDIR" == "" ]; then
    TMPDIR=./tools
fi

TempAppleScriptFileName="${TMPDIR}/${SevenriInstanceName}.applescript.tmp"

# JavaVM options

DefaultSetupJVMOptions="-Dfile.encoding=UTF-8 -Dsevenri.sid.name=$SevenriInstanceName "
SetupJVMOptsEnvVarName="${SevenriInstanceName}_SETUP_JVM_OPTS"
SetupJVMOptions="${DefaultSetupJVMOptions}${!SetupJVMOptsEnvVarName}"
RuntimeJVMOptsEnvVarName="\$${SevenriInstanceName}_JVM_OPTS"

# Sevenri.app AppleScript

read -d '' script <<EOF
set cmd to "cd $SevenriRoot
if [ -f \$HOME/.bash_profile ]; then
    source \$HOME/.bash_profile
fi
java $SetupJVMOptions $RuntimeJVMOptsEnvVarName -cp src:lib/* Sevenri &>/dev/null &"
do shell script cmd
EOF

if [ -a $SevenriAppFileName ]; then
	rm -rf $SevenriAppFileName
fi

# Start setting up staff.

echo "Creating $SevenriInstanceName.app..."

if [ $verbose == t ]; then
    echo "AppleScript used..."
    echo ">>>"
    echo "$script"
    echo "<<<"
    echo
fi

# Double-quote $script to preserve \newline.
echo "${script}">$TempAppleScriptFileName

osacompile -o $SevenriAppFileName -x $TempAppleScriptFileName >/dev/null 2>&1
rm $TempAppleScriptFileName
cp $SevenriIconFileName $SevenriAppFileName/Contents/Resources/applet.icns

echo "Downloading required dependencies..."
lein deps

echo "Building the default project manager, Planter..."
pushd ./src/project/slix/planter >/dev/null
lein jar
popd >/dev/null

echo
echo "Sevenri is ready to start. Run 'sevenri' from the command line like this:"
echo "  sevenri ${SevenriInstanceName}"
echo "or double-click '${SevenriInstanceName}.app' from the Finder."
